# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89e3d9de9588dde70e4dbd46024597d79e01cad324295108a77c6881abaaed2ab45149cc64034173ed9dc79a78b629cb7a376fa54eb26121fcd03cd427471d7f

test:
  secret_key_base: 3cf8421dc0bb15dec5dde1ab44711baa9266d9092f38637a3f1eaddd8c0b0b56bd5e7b6c9f1f41682e549dc5c91d20b267546620aab06431dd99633148deeb40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
